# Generated by Django 3.2.9 on 2021-11-13 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('publication_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Data i czas rejestracji')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='Data i czas ostatniej aktualizacji')),
                ('first_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Imię')),
                ('last_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Nazwisko')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
        ),
    ]
